### PR TITLE
testing tak chat and config file auth

### PR DESCRIPTION
**Pull request by rutheferd**

### CODE REVIEW

**Comment by rutheferd** [comment]
TAK Chats cleanup testing successful...

**Comment by rutheferd** [comment]
Working on fixing ATR bug

**Comment by rutheferd** [comment]
ATR Fixed

**Comment by rutheferd** [comment]
Running into an attachment issue -- seems like the attachment is not demarcating between the thumbnail and the actual image. There is no way seemingly to download the full image...

**Comment by rutheferd** [comment]
> Running into an attachment issue -- seems like the attachment is not demarcating between the thumbnail and the actual image. There is no way seemingly to download the full image...

Seems like the "stored locally" is being set even though that isn't done through the code...

**Comment by rutheferd** [comment]
> > Running into an attachment issue -- seems like the attachment is not demarcating between the thumbnail and the actual image. There is no way seemingly to download the full image...
> 
> Seems like the "stored locally" is being set even though that isn't done through the code...

Ohhhhh it might be that the image is natively below the max download size!

**Review by kitplummer — APPROVED** [review]
Given the demoware nature of this - not doing a deep review.  But would really like to get this repo transferred to `getditto` or `getditto-shared` org ASAP before anything further happens with the code base.

**Pull request merged**
